CXX      := c++
CXXFLAGS := -Wall -Wextra -Werror -std=c++98

NAME     := phoneBook
SRCS     := main.cpp PhoneBook.cpp Contact.cpp
OBJS     := $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
.PHONY: all clean fclean re
